---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.postgresql
      vars:
        # postgresql_data_dir: **
        postgresql_databases:
          - name: wikijs
        postgresql_users:
          - name: wikijs
            password: mywikipwnotreally
    - role: ansible-role-wikijs
      vars:
        wikijs_dbtype: postgres
